with open("main.py", 'r', encoding="utf-8") as fp:
    a = len(fp.readlines())
with open("test.py", 'r', encoding="utf-8") as fp:
    b = len(fp.readlines())
with open("./cogs/Verify.py", 'r', encoding="utf-8") as fp:
    c = len(fp.readlines())
with open("./cogs/Registerasanexpert.py", 'r', encoding="utf-8") as fp:
    d = len(fp.readlines())
with open("./cogs/Postajob.py", 'r', encoding="utf-8") as fp:
    e = len(fp.readlines())
with open("./cogs/Offerwork.py", 'r', encoding="utf-8") as fp:
    f = len(fp.readlines())
with open("./cogs/db/chats.json", 'r', encoding="utf-8") as fp:
    g = len(fp.readlines())
with open("./cogs/db/delete_messages.json", 'r', encoding="utf-8") as fp:
    h = len(fp.readlines())
with open("./cogs/db/eqs_questions.json", 'r', encoding="utf-8") as fp:
    i = len(fp.readlines())
with open("./cogs/db/expertzahlinfos.json", 'r', encoding="utf-8") as fp:
    j = len(fp.readlines())
with open("./cogs/db/finanzen.json", 'r', encoding="utf-8") as fp:
    k = len(fp.readlines())
with open("./cogs/db/payments.json", 'r', encoding="utf-8") as fp:
    l = len(fp.readlines())
with open("./cogs/db/wasgeht.json", 'r', encoding="utf-8") as fp:
    m = len(fp.readlines())
print(a + b + c + d + e + f + g + h + i + j + k + l + m)